// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SMED_selectC
IntegerVector SMED_selectC(Function f, int n, NumericMatrix X0, NumericMatrix Xopt);
RcppExport SEXP SMED_SMED_selectC(SEXP fSEXP, SEXP nSEXP, SEXP X0SEXP, SEXP XoptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xopt(XoptSEXP);
    rcpp_result_gen = Rcpp::wrap(SMED_selectC(f, n, X0, Xopt));
    return rcpp_result_gen;
END_RCPP
}
