# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Select points using SMED
#' @export
SMED_selectC <- function(f, n, X0, Xopt) {
    .Call('SMED_SMED_selectC', PACKAGE = 'SMED', f, n, X0, Xopt)
}

