# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Select points using SMED
#'
#' SMED_selectC uses C code and should run faster than SMED_select
#'
#' @export
#' @rdname SMED_select
SMED_selectC <- function(f, n, X0, Xopt, theta = as.numeric( c())) {
    .Call(`_SMED_SMED_selectC`, f, n, X0, Xopt, theta)
}

#' Select points using SMED
#'
#' SMED_selectYC takes in Y values instead of a function. It
#' uses C code and should run faster than SMED_select
#'
#' @param Y0 Y values for X0
#' @param Yopt Y values for Xopt
#' @examples
#' n = 1
#' X0 <- matrix(c(.45,.1,.55,.9),ncol=2,byrow=TRUE)
#' Xopt <- matrix(c(.45,.5,.5,.2),ncol=2,byrow=TRUE)
#' Y0 <- c(.3,.5)
#' Yopt <- c(.2,.6)
#' SMED_selectYC(n, X0, Xopt, Y0, Yopt)
#'
#' @export
#' @rdname SMED_select
SMED_selectYC <- function(n, X0, Xopt, Y0, Yopt, theta = as.numeric( c())) {
    .Call(`_SMED_SMED_selectYC`, n, X0, Xopt, Y0, Yopt, theta)
}

